update

diff --git a/.github/workflows/charts.yaml b/.github/workflows/charts.yaml
--- a/.github/workflows/charts.yaml
+++ b/.github/workflows/charts.yaml
@@ -66,29 +66,26 @@ jobs:
 
       - name: Helm diff check
         run: |
-            for i in ${{ env.REPOS }}; do
-              echo "Checking helm diff for $i"
-
-              if helm diff upgrade $i ./charts/$i \
-                -n ${{ env.ENVIRONMENT }} \
-                --set image.tag=${{ env.VERSION }} \
-                -f charts/$i/values.yaml; then
-                echo "✅ No changes detected for $i"
-              else
-                echo "❌ Changes detected for $i, aborting deployment"
-                exit 1
-              fi
-            done
-
-      - name: Check status
-        run: |
           for i in ${{ env.REPOS }}; do
-            echo "Checking helm status for $i..."
+            if [ -z "$i" ]; then
+              echo "❌ Empty repo name, skipping..."
+              continue
+            fi
 
-            if helm status $i -n ${{ env.ENVIRONMENT }}; then
-              echo "✅ $i is deployed"
+            CHART_PATH="./charts/$i"
+            if [ ! -d "$CHART_PATH" ]; then
+              echo "❌ Chart path $CHART_PATH does not exist, skipping..."
+              continue
+            fi
+
+            echo "Checking helm diff for $i"
+            if helm diff upgrade "$i" "$CHART_PATH" \
+              -n "${{ env.ENVIRONMENT }}" \
+              --set image.tag="${{ env.VERSION }}" \
+              -f "$CHART_PATH/values.yaml"; then
+              echo "✅ No changes detected for $i"
             else
-              echo "❌ $i is not deployed, aborting deployment"
+              echo "❌ Changes detected for $i, aborting deployment"
               exit 1
             fi
           done
@@ -109,3 +106,16 @@ jobs:
                   exit 1
                 fi
             done
+
+      - name: Check status
+        run: |
+          for i in ${{ env.REPOS }}; do
+            echo "Checking helm status for $i..."
+
+            if helm status $i -n ${{ env.ENVIRONMENT }}; then
+              echo "✅ $i is deployed"
+            else
+              echo "❌ $i is not deployed, aborting deployment"
+              exit 1
+            fi
+          done
